Annotate a CSV with plate/well metadata
cytomining/cytotools pull request #18
Opened 2017-12-04 19:19 UTC by mcquin

Resolves #13 

To Dos:
- [ ] test external metadata
- [ ] test format_broad_cmap
- [ ] test `"genetic"` perturbation mode
- [ ] test `cytotools_annotate` command
- [ ] test failure cases (missing batch ID/plate ID subdirectories, etc.)
- [ ] make Travis happy 😄 ❤️

2017-12-11 17:35 UTC, shntnu commented
I used `.data` to overcome the "no visible bindings issue"
https://stackoverflow.com/questions/9439256/how-can-i-handle-r-cmd-check-no-visible-binding-for-global-variable-notes-when
I previously had used `rlang::sym` to overcome this
https://github.com/cytomining/cytominer/blob/649ba287f7f8ff7faa0992fba276ebee1d22354f/R/drop_na_columns.R#L35-L39
but changed my mind after reading 

https://community.rstudio.com/t/should-tidyeval-be-abandoned/
especially
https://community.rstudio.com/t/should-tidyeval-be-abandoned/2238/5

I find tidyeval very helpful but it does cause some headaches. I anticipate this getting easier over the next year once it matures.

2017-12-11 17:36 UTC, shntnu approved these changes

2017-12-12 14:59 UTC, mcquin commented
👏 @shntnu!

2017-12-12 15:52 UTC, shntnu commented on R/annotate.R
> +#' @param external_metadata   Optional external metadata to join with, as a JSON file. default: \code{NULL}.
as a CSV file, not JSON

2017-12-12 17:32 UTC, shntnu reviewed
@mcquin thanks for adding that test!

2017-12-12 17:34 UTC, shntnu commented on tests/testthat/test-annotate.R
> +  external_metadata <- tibble(
`dplyr::tibble`

2017-12-12 17:35 UTC, shntnu commented on tests/testthat/test-annotate.R
> +  external_metadata <- tibble(
`dplyr::tibble`

2017-12-12 17:37 UTC, shntnu requested changes
Looks good except for two changes suggested. Awesome that we have a test for external metadata!

2017-12-12 18:33 UTC, shntnu reviewed
Minor fix for docs, looks good @mcquin !

2017-12-12 18:33 UTC, shntnu approved these changes

2017-12-14 15:21 UTC, merged