[WIP] Implement sample
cytomining/cytotools pull request #25
Opened 2018-01-25 20:21 UTC by mcquin

Resolves #14

2018-01-25 21:37 UTC, mcquin commented on R/sample.R
> +      dplyr::arrange(Assay_Plate_Barcode) %>%
sample: no visible binding for global variable ‘Assay_Plate_Barcode’

2018-01-25 21:38 UTC, mcquin commented on R/sample.R
> +        replicate_id = dplyr::dense_rank(.data$Assay_Plate_Barcode)) %>%
sample: no visible binding for global variable ‘replicate_id’

2018-01-29 15:38 UTC, mcquin commented on R/sample.R
> +      dplyr::arrange(Assay_Plate_Barcode) %>%
I'm unsure how to resolve this as the documentation states the arguments should be unquoted variable names:

> .data A tbl. All main verbs are S3 generics and provide methods for tbl_df(), dtplyr::tbl_dt() and dbplyr::tbl_dbi().
> ...  **Comma separated list of unquoted variable names.** Use desc() to sort a variable in descending order.
> .by_group If TRUE, will sort first by grouping variable. Applies to grouped data frames only.

2018-01-29 17:27 UTC, shntnu commented on tests/testthat/test-sample.R
> +  expect_equal(dim(actual)[1], 30)
Excellent!

2018-01-29 17:27 UTC, shntnu approved these changes
Looks good! I made some formatting changes using styler + added docs. All set.

2018-01-29 17:31 UTC, mcquin commented
Thanks, @shntnu! ✨

2018-01-29 17:47 UTC, cells2numbers requested changes
Looks good! I agree with Shantanu. Some small changes before we can merge!

2018-01-29 17:47 UTC, cells2numbers commented on R/sample.R
> +  backend_dir <- paste(workspace_dir, "backend", batch_id, sep = "/")
instead of paste(workspace_dir, "backend", batch_id, sep = "/") use file.path(workspace_dir, "backend", batch_id)

2018-01-29 17:47 UTC, cells2numbers commented on R/sample.R
> +  metadata_dir <- paste(workspace_dir, "metadata", batch_id, sep = "/")
file.path() is better suited then paste()

2018-01-29 17:47 UTC, cells2numbers commented on R/sample.R
> +          paste(metadata_dir, "barcode_platemap.csv", sep = "/"),
replace paste() with file.path()

2018-01-29 17:47 UTC, cells2numbers commented on R/sample.R
> +            paste(file_list, collapse = "\n"))
replace paste() with file.path()

2018-01-29 17:47 UTC, cells2numbers commented on R/sample.R
> +#' @param output          Output file - either CSV or RDS.
Do we also allow feather data format as output?

2018-01-29 17:47 UTC, cells2numbers commented on inst/scripts/cytotools_sample
> +  -o <file> --output=<file>             Output file - either csv or rds.
do we allow feather, too?

2018-01-29 18:14 UTC, shntnu commented on inst/scripts/cytotools_sample
> +  -o <file> --output=<file>             Output file - either csv or rds.
Good catch - yes

2018-01-29 20:24 UTC, shntnu approved these changes

2018-01-30 14:58 UTC, cells2numbers approved these changes

2018-01-30 15:06 UTC, merged